In [1]:
import os
import shutil
import nibabel as nib
import numpy as np
from glob import glob
import SimpleITK as sitk

source = glob('/home/sc-mlsg/Downloads/Meningioma_nii_preprocessed/**/*.nii*')
print(len(source))

3


In [3]:
# check same patient has same img orientation
pt_lst = []
for file in source:
    pt = file.split(os.path.sep)[-2]
    # load img
    img = nib.load(file)
    #print(file)
    if nib.aff2axcodes(img.affine) != ('L', 'P', 'S'):
        print(nib.aff2axcodes(img.affine))            
        print(os.basename(file))
        pt_lst.append(pt)
    print()

print(set(pt_lst))





set()


In [4]:
# reorient both image and header(practice)
total = 0
lst = []
for filepath in source[:1]:
    total+=1
    # load img
    img = nib.load(filepath)
    print(nib.aff2axcodes(img.affine))
    
    # only when the image orientation is LPS -> 
    if nib.aff2axcodes(img.affine)[0] == 'L':
        print(filepath.split(os.path.sep)[-1])
        # print orientation of original img
        print(nib.aff2axcodes(img.affine))
        sitk_img = sitk.ReadImage(filepath)
        print(np.array(sitk_img.GetDirection()).reshape(3,3))
        
        # reorient img(use np.flip or np.transpose)
        img_data = sitk.GetArrayFromImage(sitk_img)
        img_T = np.flip(img_data, axis=1) # LPS -> LAS
        img_T = img_T.transpose(0, 2, 1)  # LAS -> LSA              # PSL -> LPS
        
        # reset image header info
        flipFilter = sitk.FlipImageFilter()
        flipAxes = (False, True, False) #(width, height, depth)
        flipFilter.SetFlipAxes(flipAxes)
        temp_img = flipFilter.Execute(sitk_img)
        new_img = sitk.PermuteAxes(temp_img, [0,2,1])
        
        # save new header info
        ni_img = sitk.GetImageFromArray(img_T)
        ni_img.SetOrigin(new_img.GetOrigin())
        ni_img.SetSpacing(new_img.GetSpacing())
        ni_img.SetDirection(new_img.GetDirection())
        
        # save file
        outpath = os.path.join(os.path.dirname(filepath), os.path.basename(filepath).split('.')[0]+'_flipped.nii.gz')
        sitk.WriteImage(ni_img, outpath)
        
        # check orientation of reoriented img
        img = nib.load(outpath)
        print(nib.aff2axcodes(img.affine))
        
        sitk_mask = sitk.ReadImage(outpath)
        print(np.array(sitk_mask.GetDirection()).reshape(3,3))

('L', 'P', 'S')
8155858_brain_mask.nii.gz
('L', 'P', 'S')
[[ 0.99978019 -0.00398073  0.02058471]
 [ 0.00529207  0.9979328  -0.06404776]
 [-0.0202872   0.06414262  0.99773451]]
('L', 'S', 'A')
[[ 0.99978025  0.02058108  0.0039846 ]
 [ 0.0052957  -0.06404777 -0.99793278]
 [-0.02028333  0.99773458 -0.0641427 ]]


In [15]:
# reorient both image and header
total = 0
lst = []
for filepath in source[:1]:
    total+=1
    # load img
    img = nib.load(filepath)
    print(nib.aff2axcodes(img.affine))
    
    # only when the image orientation is PIL -> LPS
    if nib.aff2axcodes(img.affine)[0] == 'P':
        print(filepath.split(os.path.sep)[-1])
        # print orientation of original img
        print(nib.aff2axcodes(img.affine))
        sitk_img = sitk.ReadImage(filepath)
        print(np.array(sitk_img.GetDirection()).reshape(3,3))
        
        # reorient img(use np.flip or np.transpose)
        img_data = sitk.GetArrayFromImage(sitk_img)
        img_T = np.flip(img_data, axis=1) # PIL -> PSL
        img_T = img_T.transpose(0, 2, 1)  # PSL -> LPS
        
        # reset image header info
        flipFilter = sitk.FlipImageFilter()
        flipAxes = (False, True, False) #(width, height, depth)
        flipFilter.SetFlipAxes(flipAxes)
        temp_img = flipFilter.Execute(sitk_img)
        new_img = sitk.PermuteAxes(temp_img, [0,2,1])
        
        # save new header info
        ni_img = sitk.GetImageFromArray(img_T)
        ni_img.SetOrigin(new_img.GetOrigin())
        ni_img.SetSpacing(new_img.GetSpacing())
        ni_img.SetDirection(new_img.GetDirection())
        
        # save file
        outpath = os.path.join(os.path.dirname(filepath), os.path.basename(filepath).split('.')[0]+'_flipped.nii.gz')
        sitk.WriteImage(ni_img, outpath)
        
        # check orientation of reoriented img
        img = nib.load(outpath)
        print(nib.aff2axcodes(img.affine))
        
        sitk_mask = sitk.ReadImage(outpath)
        print(np.array(sitk_mask.GetDirection()).reshape(3,3))

    # only when the image orientation is LIP -> LPS
    if nib.aff2axcodes(img.affine)[-1] == 'P':
        print(filepath.split(os.path.sep)[-1])
        # print orientation of original img
        print(nib.aff2axcodes(img.affine))
        sitk_img = sitk.ReadImage(filepath)
        print(np.array(sitk_img.GetDirection()).reshape(3,3))
        
        # reorient img(use np.flip or np.transpose)
        img_data = sitk.GetArrayFromImage(sitk_img)
        img_T = np.flip(img_data, axis=1) # LIP -> LSP
        img_T = img_T.transpose(0, 2, 1)  # LSP -> LPS
        
        # reset image header info
        flipFilter = sitk.FlipImageFilter()       
        flipAxes = (False, True, False) #(width, height, depth)
        flipFilter.SetFlipAxes(flipAxes)
        temp_img = flipFilter.Execute(sitk_img)
        new_img = sitk.PermuteAxes(temp_img, [0,2,1])
        
        # save new header info
        ni_img = sitk.GetImageFromArray(img_T)
        ni_img.SetOrigin(new_img.GetOrigin())
        ni_img.SetSpacing(new_img.GetSpacing())
        ni_img.SetDirection(new_img.GetDirection())
        
        # save file
        outpath = os.path.join(os.path.dirname(filepath), os.path.basename(filepath).split('.')[0]+'_flipped.nii.gz')
        sitk.WriteImage(ni_img, outpath)
        
        # check orientation of reoriented img
        img = nib.load(outpath)
        print(nib.aff2axcodes(img.affine))
        
        sitk_mask = sitk.ReadImage(outpath)
        print(np.array(sitk_mask.GetDirection()).reshape(3,3))


('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
[[-3.50859873e-02  1.10959041e-02  9.99322698e-01]
 [ 9.52811240e-01 -3.01324732e-01  3.67987151e-02]
 [-3.01528960e-01 -9.53457019e-01  2.71287078e-08]]
('P', 'L', 'S')
[[-3.50859099e-02  9.99322695e-01 -1.10963646e-02]
 [ 9.52811382e-01  3.67987820e-02  3.01324272e-01]
 [-3.01528520e-01  5.07227801e-07  9.53457159e-01]]


In [ ]:
# reorient **image only**
for filepath in source[:20]:
    # load img
    img = nib.load(filepath)    
    if nib.aff2axcodes(img.affine)[0] == 'P': # img: LPI (-> PIL), header:PIL 
        print(filepath.split(os.path.sep)[-2], filepath.split(os.path.sep)[-1])
        # print orientation of original img
        print(nib.aff2axcodes(img.affine))
        sitk_img = sitk.ReadImage(filepath)
        
        # reorient img(use np.flip or np.transpose)
        img_data = sitk.GetArrayFromImage(sitk_img)
        img_T = img_data.transpose(1, 0, 2) # LPI -> PLI
#        img_T = np.flip(img_T, axis=2)
                
        # save file
        outpath = os.path.join(os.path.dirname(filepath), os.path.basename(filepath).split('.')[0]+'_flipped.nii.gz')
        ni_img = nib.Nifti1Image(img_T, img.affine, img.header)
        nib.save(ni_img, outpath)
                
        # check orientation of reoriented img
        img = nib.load(outpath)
        print(nib.aff2axcodes(img.affine))
        
        sitk_mask = sitk.ReadImage(outpath)
        print(np.array(sitk_mask.GetDirection()).reshape(3,3))
        
    if nib.aff2axcodes(img.affine)[-1] == 'A': # img: LPS -> LSA, header:LSA
        print(filepath.split(os.path.sep)[-2], filepath.split(os.path.sep)[-1])
        # print orientation of original img
        print(nib.aff2axcodes(img.affine))
        sitk_img = sitk.ReadImage(filepath)
        
        # reorient img(use np.flip or np.transpose)
        img_data = sitk.GetArrayFromImage(sitk_img)
        img_T = img_data.transpose(2, 0, 1) # LPS -> LSP
        img_T = np.flip(img_T, axis=1) # LSP -> LSA
                
        # save file
        outpath = os.path.join(os.path.dirname(filepath), os.path.basename(filepath).split('.')[0]+'_flipped_2.nii.gz')
        ni_img = nib.Nifti1Image(img_T, img.affine, img.header)
        nib.save(ni_img, outpath)
                
        # check orientation of reoriented img
        img = nib.load(outpath)
        print(nib.aff2axcodes(img.affine))
        
        sitk_mask = sitk.ReadImage(outpath)
        print(np.array(sitk_mask.GetDirection()).reshape(3,3))
