brain image shape and mask shape

In [2]:
import os
import shutil
import nibabel as nib
import numpy as np
from glob import glob
import SimpleITK as sitk

In [3]:
raw_flair = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics/**/*FLAIR*')
raw_mask = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics/**/*mask*')
resampled_flair = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics_preprocessed/01_Resampled/**/*FLAIR*')
resampled_mask = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics_preprocessed/00_Tumor_masks_resampled/**/*mask*')

registered = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics_preprocessed/03_Registered_corrected/**/*FLAIR*')
registered_flair = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics_preprocessed/03_Registered_corrected/**/*FLAIR*')
#registered_mask = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics_preprocessed/03_Registered_corrected/**/*mask*')

### raw file

In [26]:
raw_flair = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics/**/*FLAIR*')
raw_mask = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics/**/*mask*')

raw_pt = []
for f, m in zip(raw_flair, raw_mask):
    sitk_img = sitk.ReadImage(f)
    sitk_mask = sitk.ReadImage(m)
    img_d = np.array(sitk_img.GetDirection()).reshape(3,3)
    mask_d = np.array(sitk_mask.GetDirection()).reshape(3,3)
    if img_d[1,1] * mask_d[1,1] < 0:
        print(f.split(os.path.sep)[-1])
        print(img_d)
        print(mask_d)
        raw_pt.append(f.split(os.path.sep)[-1].split("_")[0])

2803895_FLAIR.nii.gz
[[ 0.99942672  0.01426985 -0.03070198]
 [-0.00587011  0.96613769  0.25796028]
 [ 0.03334339 -0.25763216  0.96566758]]
[[ 0.99942676 -0.01426965 -0.03070047]
 [-0.00587031 -0.96613769  0.25796029]
 [ 0.03334188  0.25763218  0.96566763]]
3621229_FLAIR.nii.gz
[[ 0.99753852  0.01417    -0.0686739 ]
 [-0.00432267  0.98993305  0.14147041]
 [ 0.06998719 -0.14082534  0.9875576 ]]
[[ 0.99753843 -0.0141701  -0.06867527]
 [-0.00432257 -0.98993305  0.1414704 ]
 [ 0.06998857  0.14082531  0.98755751]]
4199579_FLAIR.nii.gz
[[ 9.99479984e-01 -3.19197522e-02 -4.57071039e-03]
 [ 3.22453367e-02  9.89388017e-01  1.41674256e-01]
 [-1.83981151e-10 -1.41747953e-01  9.89902780e-01]]
[[ 9.99480013e-01  3.19206644e-02 -4.55784912e-03]
 [ 3.22444213e-02 -9.89388017e-01  1.41674443e-01]
 [-1.28613077e-05  1.41747745e-01  9.89902812e-01]]
5096558_FLAIR.nii.gz
[[ 0.99869055 -0.05115852  0.        ]
 [ 0.05115852  0.99869055  0.        ]
 [ 0.          0.          1.        ]]
[[ 0.99869055  0.0

7922825_FLAIR.nii.gz
[[ 9.99887129e-01  1.49908518e-02  1.00211811e-03]
 [-1.50243092e-02  9.97660472e-01  6.66922196e-02]
 [ 1.44848381e-11 -6.66997523e-02  9.97773092e-01]]
[[ 9.99887254e-01 -1.50075816e-02  5.01058849e-04]
 [-1.50075815e-02 -9.97660472e-01  6.66959859e-02]
 [ 5.01058851e-04  6.66959871e-02  9.97773218e-01]]
7938576_FLAIR.nii.gz
[[ 9.99541743e-01  6.14029612e-03 -2.96411922e-02]
 [-9.90339685e-11  9.79210343e-01  2.02847483e-01]
 [ 3.02705030e-02 -2.02754536e-01  9.78761615e-01]]
[[ 9.99541765e-01 -6.14022210e-03 -2.96404689e-02]
 [-7.42506724e-08 -9.79210342e-01  2.02847482e-01]
 [ 3.02697822e-02  2.02754539e-01  9.78761637e-01]]
7947384_FLAIR.nii.gz
[[ 0.99722139 -0.06355594 -0.03886058]
 [ 0.06535163  0.99676281  0.04683025]
 [ 0.03575844 -0.04923972  0.99814667]]
[[ 0.99722136  0.06355592 -0.03886129]
 [ 0.06535165 -0.99676281  0.04683022]
 [ 0.03575915  0.04923975  0.99814665]]
7968300_FLAIR.nii.gz
[[ 0.99168012 -0.12872659  0.        ]
 [ 0.12872659  0.99168012

8491797_FLAIR.nii.gz
[[ 9.99653822e-01 -2.62012384e-02  2.39420033e-03]
 [-2.63102987e-02 -9.95254673e-01  9.36797903e-02]
 [ 7.16872916e-05  9.37103543e-02  9.95599500e-01]]
[[ 9.99653736e-01  2.61978719e-02  2.46588728e-03]
 [-2.63136671e-02  9.95254673e-01  9.36788414e-02]
 [-1.23571403e-10 -9.37112934e-02  9.95599414e-01]]
8491887_FLAIR.nii.gz
[[ 0.99726833 -0.06778977 -0.02933307]
 [ 0.07198058  0.98102681  0.1800144 ]
 [ 0.0165734  -0.18163407  0.98322652]]
[[ 0.99726831  0.0677897  -0.02933381]
 [ 0.07198065 -0.98102682  0.18001437]
 [ 0.01657413  0.18163409  0.9832265 ]]
8494094_FLAIR.nii.gz
[[ 0.99593014  0.08936939 -0.01167305]
 [-0.08726625  0.9885605   0.12301518]
 [ 0.02253331 -0.12149587  0.99233614]]
[[ 0.99593023 -0.08936909 -0.01166815]
 [-0.08726655 -0.9885605   0.12301498]
 [ 0.0225284   0.12149609  0.99233622]]
8513671_FLAIR.nii.gz
[[ 9.98839879e-01 -4.09485310e-03 -4.79804851e-02]
 [-1.16217476e-10  9.96377964e-01 -8.50350136e-02]
 [ 4.81549103e-02  8.49363578e-02 

In [27]:
sorted(raw_pt)

['2803895',
 '3621229',
 '4199579',
 '5096558',
 '5792723',
 '6291624',
 '6645678',
 '6659190',
 '6673952',
 '6715199',
 '6776630',
 '6830738',
 '7547026',
 '7553272',
 '7644780',
 '7707348',
 '7711873',
 '7716992',
 '7741219',
 '7767219',
 '7777703',
 '7783083',
 '7808217',
 '7809569',
 '7816559',
 '7820534',
 '7826770',
 '7865431',
 '7871704',
 '7892450',
 '7898233',
 '7921035',
 '7922825',
 '7938576',
 '7947384',
 '7968300',
 '7971571',
 '7973273',
 '8002014',
 '8011880',
 '8044835',
 '8051568',
 '8052811',
 '8072260',
 '8074420',
 '8077298',
 '8083396',
 '8089351',
 '8097929',
 '8101370',
 '8125034',
 '8170673',
 '8190372',
 '8224960',
 '8229739',
 '8235696',
 '8268889',
 '8367857',
 '8450356',
 '8481377',
 '8484226',
 '8489830',
 '8491797',
 '8491887',
 '8494094',
 '8513671',
 '8529533',
 '8532530',
 '8536936',
 '8549991',
 '8562189',
 '8566583',
 '8588494',
 '8595211',
 '8604413',
 '8647046',
 '8665561',
 '8712859',
 '8736560',
 '8737593',
 '8739559',
 '8747465',
 '8784152',
 '87

In [28]:
len(raw_pt)

87

mask files were flipped from the raw files.

In [15]:
os.path.dirname(f)

'/media/sc-mlsg/DATA2/Perfusion_study_radiomics/8536936'

In [24]:
raw_flair = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics/**/*FLAIR*')
raw_mask = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics/**/*mask*')

raw_pt = []
for f, m in zip(raw_flair[:3], raw_mask[:3]):
    sitk_img = sitk.ReadImage(f)
    sitk_mask = sitk.ReadImage(m)
    img_d = np.array(sitk_img.GetDirection()).reshape(3,3)
    mask_d = np.array(sitk_mask.GetDirection()).reshape(3,3)
    if img_d[1,1] * mask_d[1,1] < 0:
        print(f.split(os.path.sep)[-1])
        print(mask_d)
        mask = nib.load(m)
        mask_data = mask.get_fdata()
        
        mask_T = np.flip(mask_data, axis=0)
        
        ni_img = nib.Nifti1Image(mask_T, mask.affine, mask.header)
        
        outPath = os.path.join(os.path.dirname(m), m.split(os.path.sep)[-1].split('.')[0] + '_flipped.nii')
        print(outPath)
        nib.save(ni_img, outPath)
        
        sitk_mask2 = sitk.ReadImage(outPath)
        mask_d = np.array(sitk_mask2.GetDirection()).reshape(3,3)
        print(mask_d)


2803895_FLAIR.nii.gz
[[ 0.99942676 -0.01426965 -0.03070047]
 [-0.00587031 -0.96613769  0.25796029]
 [ 0.03334188  0.25763218  0.96566763]]
/media/sc-mlsg/DATA2/Perfusion_study_radiomics/2803895/2803895_mask_flipped.nii
[[ 0.99942676 -0.01426965 -0.03070047]
 [-0.00587031 -0.96613769  0.25796029]
 [ 0.03334188  0.25763218  0.96566763]]


### raw mask vs resampled mask

In [5]:
re_mask = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics_preprocessed/00_Tumor_masks_resampled/**/*mask*')
raw_mask = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics/**/*mask*')

mask_pt = []
for f, m in zip(re_mask, raw_mask):
    sitk_img = sitk.ReadImage(f)
    sitk_mask = sitk.ReadImage(m)
    img_d = np.array(sitk_img.GetDirection()).reshape(3,3)
    mask_d = np.array(sitk_mask.GetDirection()).reshape(3,3)
    if not np.array_equal(img_d, mask_d):
        print(f.split(os.path.sep)[-1])
        print(img_d)
        print(mask_d)
        mask_pt.append(f.split(os.path.sep)[-1].split("_")[0])

2034571_mask.nii
[[ 0.99857121  0.03452456 -0.04078725]
 [-0.03760892  0.99628693 -0.0774463 ]
 [ 0.03796201  0.07886961  0.99616187]]
[[ 0.99857124  0.03452351 -0.04078722]
 [-0.03760787  0.99628696 -0.07744632]
 [ 0.03796205  0.07886958  0.99616187]]
2803895_mask.nii
[[ 0.99942676 -0.01426965 -0.03070047]
 [-0.00587031 -0.96613769  0.2579603 ]
 [ 0.03334188  0.25763219  0.96566763]]
[[ 0.99942676 -0.01426965 -0.03070047]
 [-0.00587031 -0.96613769  0.25796029]
 [ 0.03334188  0.25763218  0.96566763]]
2826490_mask.nii
[[ 0.99341597  0.08154954  0.08046352]
 [ 0.08473589 -0.99571594 -0.03700817]
 [-0.07710081 -0.04358265  0.99607029]]
[[ 0.99341597  0.08154954  0.08046352]
 [ 0.08473589 -0.99571594 -0.03700816]
 [-0.07710081 -0.04358265  0.99607029]]
2917442_mask.nii
[[ 9.94716983e-01 -3.00616718e-03 -1.02611342e-01]
 [-4.25720274e-05  9.99558963e-01 -2.96964110e-02]
 [ 1.02655357e-01  2.95438928e-02  9.94278148e-01]]
[[ 9.94716919e-01 -3.04873958e-03 -1.02610706e-01]
 [-1.41120797e-10  

7741219_mask.nii
[[ 9.97971925e-01 -7.50272618e-03 -6.32119086e-02]
 [-9.36198010e-08 -9.93029879e-01  1.17862877e-01]
 [ 6.36556057e-02  1.17623842e-01  9.91015942e-01]]
[[ 9.97971925e-01 -7.50272657e-03 -6.32119113e-02]
 [-9.36198036e-08 -9.93029879e-01  1.17862884e-01]
 [ 6.36556097e-02  1.17623847e-01  9.91015941e-01]]
7746738_mask.nii
[[ 0.99702806  0.06380707  0.04317062]
 [-0.07078913  0.97988422  0.18658994]
 [-0.03039645 -0.18909142  0.98148892]]
[[ 0.99702803  0.06380751  0.04317067]
 [-0.07078956  0.9798842   0.18658992]
 [-0.03039641 -0.18909141  0.98148892]]
7753977_mask.nii
[[ 0.99799153  0.06035663 -0.01923501]
 [-0.05660646  0.985989    0.15691208]
 [ 0.02843619 -0.15550812  0.98742524]]
[[ 0.99799151  0.06035698 -0.01923498]
 [-0.05660681  0.98598898  0.1569121 ]
 [ 0.02843622 -0.15550811  0.98742524]]
7760652_mask.nii
[[ 9.99160334e-01  2.71062524e-03 -4.08812714e-02]
 [-1.36503266e-05  9.97831026e-01  6.58273829e-02]
 [ 4.09710364e-02 -6.57715486e-02  9.96993218e-01]

8002014_mask.nii
[[ 0.99665843  0.08020926  0.01544155]
 [ 0.07760899 -0.98883621  0.12719986]
 [-0.02547177  0.1255764   0.9917569 ]]
[[ 0.99665844  0.08020926  0.01544143]
 [ 0.07760901 -0.9888362   0.12719987]
 [-0.02547166  0.12557643  0.9917569 ]]
8011358_mask.nii
[[ 0.99809095  0.05297156 -0.03175631]
 [-0.0539543   0.9980642  -0.03093186]
 [ 0.03005632  0.0325862   0.9990169 ]]
[[ 9.99424662e-01 -1.18159599e-03 -3.38961493e-02]
 [-5.12628970e-08 -9.99393020e-01  3.48366275e-02]
 [ 3.39167382e-02  3.48165840e-02  9.98818032e-01]]
8011880_mask.nii
[[ 9.99424662e-01 -1.18159593e-03 -3.38961516e-02]
 [-5.12046880e-08 -9.99393020e-01  3.48366273e-02]
 [ 3.39167388e-02  3.48165846e-02  9.98818032e-01]]
[[ 0.99989016  0.0113387   0.0095447 ]
 [-0.0103824   0.99543487 -0.09487878]
 [-0.0105767   0.09476738  0.99544307]]
8037487_mask.nii
[[ 0.99590876  0.0838507  -0.03368694]
 [-0.07736402  0.98381018  0.16165499]
 [ 0.04669644 -0.15838747  0.9862722 ]]
[[ 0.99590873  0.08385103 -0.03368

8484226_mask.nii
[[ 0.99852341  0.01137767 -0.05311831]
 [ 0.01285404 -0.99953818  0.0275356 ]
 [ 0.05278049  0.02817772  0.99820851]]
[[ 0.99852341  0.01137767 -0.05311831]
 [ 0.01285404 -0.99953818  0.0275356 ]
 [ 0.05278049  0.02817772  0.99820851]]
8485609_mask.nii
[[ 0.99641898 -0.08454385 -0.00124919]
 [ 0.08346794  0.98116439  0.17421119]
 [-0.01350282 -0.1736916   0.98470752]]
[[ 0.99641899 -0.08454366 -0.00124918]
 [ 0.08346774  0.98116441  0.17421117]
 [-0.0135028  -0.17369161  0.98470752]]
8489830_mask.nii
[[ 9.99933266e-01 -1.06027956e-02  4.58737463e-03]
 [-1.15525446e-02 -9.19254552e-01  3.93494100e-01]
 [-4.48272196e-05  3.93520837e-01  9.19315696e-01]]
[[ 9.99933266e-01 -1.06027936e-02  4.58737880e-03]
 [-1.15525443e-02 -9.19254544e-01  3.93494110e-01]
 [-4.48317675e-05  3.93520856e-01  9.19315692e-01]]
8491797_mask.nii
[[ 9.99653822e-01  2.61946024e-02  2.46573409e-03]
 [-2.63103975e-02  9.95254759e-01  9.36788493e-02]
 [-1.53350371e-07 -9.37112946e-02  9.95599414e-01]

8662383_mask.nii
[[ 0.99969277  0.02380141 -0.00691861]
 [ 0.02349298 -0.99885463 -0.04168348]
 [ 0.00790281 -0.04150813  0.99910691]]
[[ 0.9955871   0.09382601  0.00173435]
 [ 0.09353694 -0.99069177 -0.0988972 ]
 [ 0.00756092 -0.09862301  0.99509614]]
8664725_mask.nii
[[ 9.99999986e-01 -1.67854818e-04  4.75245895e-06]
 [-1.67854812e-04 -9.98398028e-01  5.65804714e-02]
 [ 4.75245900e-06  5.65804740e-02  9.98398042e-01]]
[[ 0.9998406   0.01699823  0.0054613 ]
 [ 0.01618993 -0.9921461   0.12403223]
 [-0.00752674  0.12392405  0.99226316]]
8665561_mask.nii
[[ 0.99867052  0.03496182  0.0378797 ]
 [ 0.02948058 -0.99017781  0.13667041]
 [-0.04228588  0.13537198  0.98989208]]
[[ 0.99772424  0.04840293 -0.04694149]
 [ 0.05150697 -0.99639962  0.06734116]
 [ 0.04351298  0.06960573  0.99662514]]
8695364_mask.nii
[[ 0.99962762  0.01727076 -0.02112703]
 [ 0.02049484 -0.9863462   0.16340486]
 [ 0.01801644  0.163777    0.98633286]]
[[ 9.91257882e-01 -7.22285323e-02 -1.10412187e-01]
 [-7.17845981e-02 -

In [6]:
len(mask_pt)

133

### resampled file

In [ ]:
re_flair = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics_preprocessed/01_Resampled/**/*FLAIR*')
re_mask = glob('/media/sc-mlsg/DATA2/Perfusion_study_radiomics/**/*mask*')

raw_pt = []
for f, m in zip(raw_flair, raw_mask):
    sitk_img = sitk.ReadImage(f)
    sitk_mask = sitk.ReadImage(m)
    img_d = np.array(sitk_img.GetDirection()).reshape(3,3)
    mask_d = np.array(sitk_mask.GetDirection()).reshape(3,3)
    if not np.array_equal(img_d, mask_d):
        print(f.split(os.path.sep)[-1])
        print(img_d)
        print(mask_d)
        raw_pt.append(f.split(os.path.sep)[-1].split("_")[0])

In [21]:
for f, m in zip(registered_flair, resampled_mask):
    sitk_img = sitk.ReadImage(f)
    sitk_mask = sitk.ReadImage(m)
    img_d = np.array(sitk_img.GetDirection()).reshape(3,3)
    mask_d = np.array(sitk_mask.GetDirection()).reshape(3,3)
    if not np.array_equal(img_d, mask_d):
        print(f.split(os.path.sep)[-1])
        print(img_d)
        print(mask_d)

2034571_FLAIR_registered.nii.gz
[[ 0.99857121  0.03452454 -0.04078725]
 [-0.0376089   0.99628693 -0.0774463 ]
 [ 0.03796201  0.07886962  0.99616187]]
[[ 0.99857121  0.03452456 -0.04078725]
 [-0.03760892  0.99628693 -0.0774463 ]
 [ 0.03796201  0.07886961  0.99616187]]
2803895_FLAIR_registered.nii.gz
[[ 0.99942676  0.01426582 -0.0307025 ]
 [-0.00586608  0.96613774  0.2579602 ]
 [ 0.03334286 -0.25763222  0.96566759]]
[[ 0.99942676 -0.01426965 -0.03070047]
 [-0.00587031 -0.96613769  0.2579603 ]
 [ 0.03334188  0.25763219  0.96566763]]
2826490_FLAIR_registered.nii.gz
[[ 0.99341597  0.08154954  0.08046352]
 [ 0.08473589 -0.99571594 -0.03700817]
 [-0.07710081 -0.04358266  0.99607029]]
[[ 0.99341597  0.08154954  0.08046352]
 [ 0.08473589 -0.99571594 -0.03700817]
 [-0.07710081 -0.04358265  0.99607029]]
2917442_FLAIR_registered.nii.gz
[[ 9.94716983e-01 -3.00668243e-03 -1.02611327e-01]
 [-4.20566968e-05  9.99558963e-01 -2.96964389e-02]
 [ 1.02655357e-01  2.95438667e-02  9.94278149e-01]]
[[ 9.94716

7767219_FLAIR_registered.nii.gz
[[ 9.98634717e-01  5.15945895e-02  8.16699869e-03]
 [-5.22369753e-02  9.86353945e-01  1.56131984e-01]
 [ 1.39951982e-08 -1.56345429e-01  9.87702437e-01]]
[[ 9.98634720e-01 -5.15942582e-02  8.16882960e-03]
 [-5.22369308e-02 -9.86353951e-01  1.56131938e-01]
 [-1.84579544e-06  1.56345504e-01  9.87702429e-01]]
7777703_FLAIR_registered.nii.gz
[[ 0.99985743  0.01688559  0.        ]
 [-0.01688559  0.99985743  0.        ]
 [ 0.          0.          1.        ]]
[[ 0.99985755 -0.01687829  0.        ]
 [-0.01687829 -0.99985755  0.        ]
 [ 0.          0.          1.        ]]
7783083_FLAIR_registered.nii.gz
[[ 0.99180664 -0.11110303 -0.06305317]
 [ 0.11415108  0.99235176  0.04698426]
 [ 0.05735083 -0.05379689  0.99690359]]
[[ 0.99180664  0.1111035  -0.06305235]
 [ 0.11415151 -0.99235171  0.04698429]
 [ 0.05734999  0.05379685  0.99690365]]
7808217_FLAIR_registered.nii.gz
[[ 9.98872496e-01 -4.74651611e-02  8.91407559e-04]
 [ 4.74735302e-02  9.98696401e-01 -1.8755

8044835_FLAIR_registered.nii.gz
[[ 0.99661155 -0.06667735  0.04816165]
 [ 0.07395367  0.98269308 -0.16983863]
 [-0.03600373  0.17282486  0.98429431]]
[[ 0.99661155  0.06667897  0.04815942]
 [ 0.07395488 -0.98269298 -0.16983867]
 [-0.03600125 -0.1728248   0.98429442]]
8051568_FLAIR_registered.nii.gz
[[ 0.99903995 -0.00657652 -0.04331187]
 [ 0.01135826  0.99374426  0.11110059]
 [ 0.04231027 -0.11148587  0.99286492]]
[[ 0.99903995  0.00657712 -0.04331178]
 [ 0.01135885 -0.99374425  0.11110057]
 [ 0.04231011  0.11148588  0.99286492]]
8052811_FLAIR_registered.nii.gz
[[ 9.96768630e-01  7.84037725e-02  1.74684825e-02]
 [-8.03261977e-02  9.72913404e-01  2.16765332e-01]
 [-1.02084149e-07 -2.17468058e-01  9.76067438e-01]]
[[ 9.96768623e-01 -7.84055524e-02  1.74608523e-02]
 [-8.03262839e-02 -9.72913335e-01  2.16765606e-01]
 [ 7.72987391e-06  2.17467727e-01  9.76067513e-01]]
8060512_FLAIR_registered.nii.gz
[[ 0.99114939  0.10754909  0.07782077]
 [-0.10925448  0.99385106  0.01798673]
 [-0.07540779 

8513671_FLAIR_registered.nii.gz
[[ 9.98839880e-01 -4.09452578e-03 -4.79805066e-02]
 [-3.27807194e-07  9.96377964e-01 -8.50350122e-02]
 [ 4.81548955e-02  8.49363746e-02  9.95222044e-01]]
[[ 9.98839880e-01  4.09485314e-03 -4.79804768e-02]
 [ 7.26568546e-10 -9.96377963e-01 -8.50350197e-02]
 [ 4.81548955e-02 -8.49363670e-02  9.95222045e-01]]
8518093_FLAIR_registered.nii.gz
[[ 0.97642525 -0.18487349  0.11142492]
 [ 0.18432981  0.98274611  0.01525172]
 [-0.11232205  0.00564677  0.99365581]]
[[ 0.97642525 -0.18487349  0.11142492]
 [ 0.18432981  0.98274611  0.01525172]
 [-0.11232205  0.00564677  0.99365581]]
8529533_FLAIR_registered.nii.gz
[[ 0.99976566 -0.00908846 -0.01964731]
 [ 0.00865081  0.99971508 -0.02224669]
 [ 0.01984391  0.02207151  0.99955944]]
[[ 0.99976566  0.00908107 -0.01965072]
 [ 0.00864334 -0.99971515 -0.02224664]
 [ 0.01984715 -0.02207158  0.99955937]]
8532530_FLAIR_registered.nii.gz
[[ 9.99802476e-01  2.65907592e-03  1.96961745e-02]
 [-7.20559740e-04  9.95207676e-01 -9.7781

9111662_FLAIR_registered.nii.gz
[[ 0.9991487   0.02261619 -0.03450198]
 [-0.01789332  0.99115098  0.13152781]
 [ 0.03717133 -0.13079849  0.99071189]]
[[ 0.9991487  -0.02261916 -0.03450009]
 [-0.01789652 -0.99115092  0.13152783]
 [ 0.03716984  0.13079843  0.99071195]]


In [9]:
for f, m in zip(raw_flair, raw_mask):
    img = nib.load(f)
    mask = nib.load(m)
    img_data = img.get_fdata()
    mask_data = mask.get_fdata()
#    print(img_data.shape, mask_data.shape)
    if not np.array_equal(img.affine ,mask.affine):
        print(f)
        print(img.affine)
        print(mask.affine)

/media/sc-mlsg/DATA2/Perfusion_study_radiomics/2034571/2034571_FLAIR.nii.gz
[[-4.45790708e-01 -1.54122813e-02  8.15744326e-02  1.24397171e+02]
 [ 1.67892296e-02 -4.44770962e-01  1.54892653e-01  1.23819702e+02]
 [ 1.69473458e-02  3.52096371e-02  1.99232364e+00 -5.46599121e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.48576927e-01 -1.55086080e-02  2.85510510e-01  1.14839745e+02]
 [ 1.68941617e-02 -4.47550803e-01  5.42124271e-01  1.16143974e+02]
 [ 1.70532651e-02  3.54296975e-02  6.97313309e+00 -3.66847267e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
/media/sc-mlsg/DATA2/Perfusion_study_radiomics/2803895/2803895_FLAIR.nii.gz
[[-4.48961228e-01 -6.41028397e-03  2.14913845e-01  1.14872337e+02]
 [ 2.63696513e-03 -4.34007168e-01 -1.80572200e+00  1.25746231e+02]
 [ 1.49784777e-02 -1.15733199e-01  6.75967312e+00 -4.06021538e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.48961242e-01  6.41019547e-03  2.1490

/media/sc-mlsg/DATA2/Perfusion_study_radiomics/6659190/6659190_FLAIR.nii.gz
[[-4.48484659e-01  1.33010074e-02  3.42129171e-01  1.07516808e+02]
 [-1.74949318e-02 -4.39538985e-01 -1.41937757e+00  1.42246201e+02]
 [ 1.87857077e-02 -9.17935148e-02  6.84604359e+00 -6.14213371e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.48484644e-01 -1.33009235e-02  3.42142153e-01  1.14313622e+02]
 [-1.74950170e-02  4.39538984e-01 -1.41937788e+00 -8.23582230e+01]
 [ 1.87865320e-02  9.17935293e-02  6.84604596e+00 -1.08327820e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
/media/sc-mlsg/DATA2/Perfusion_study_radiomics/6673952/6673952_FLAIR.nii.gz
[[-4.48753446e-01  1.90616981e-03  3.17136168e-01  1.23231674e+02]
 [-5.85816812e-11 -4.47261304e-01  6.52765810e-01  1.07423103e+02]
 [ 2.04410031e-02  4.18472737e-02  6.96227837e+00 -5.30289001e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.48753435e-01 -1.90617511e-03  3.1713

/media/sc-mlsg/DATA2/Perfusion_study_radiomics/7783083/7783083_FLAIR.nii.gz
[[-4.45538104e-01  4.99097630e-02  4.41372216e-01  1.07483658e+02]
 [-5.12790047e-02 -4.45782989e-01 -3.28889757e-01  1.42580856e+02]
 [ 2.57630609e-02 -2.41665766e-02  6.97832489e+00 -5.31936302e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.45538139e-01 -4.99097765e-02  4.41366412e-01  1.32987549e+02]
 [-5.12789962e-02  4.45782993e-01 -3.28890037e-01 -8.52142563e+01]
 [ 2.57626892e-02  2.41665562e-02  6.97832504e+00 -6.55427551e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
/media/sc-mlsg/DATA2/Perfusion_study_radiomics/7808217/7808217_FLAIR.nii.gz
[[-4.48712200e-01  2.13231798e-02 -6.23999164e-03  1.06318039e+02]
 [-2.13269386e-02 -4.48633105e-01  1.31287426e-01  1.30850494e+02]
 [ 1.05445670e-11  8.43476411e-03  6.99876595e+00 -4.17939072e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.48712254e-01 -2.13250610e-02 -3.1199

/media/sc-mlsg/DATA2/Perfusion_study_radiomics/7968300/7968300_FLAIR.nii.gz
[[-4.45481300e-01  5.78263961e-02  0.00000000e+00  9.34965134e+01]
 [-5.78263961e-02 -4.45481300e-01  0.00000000e+00  1.41685120e+02]
 [ 0.00000000e+00  0.00000000e+00  7.00000000e+00 -3.47009430e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.45481306e-01 -5.78263916e-02  0.00000000e+00  1.23045799e+02]
 [-5.78263916e-02  4.45481306e-01  0.00000000e+00 -8.59558258e+01]
 [ 0.00000000e+00  0.00000000e+00  7.00000000e+00 -3.47009430e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
/media/sc-mlsg/DATA2/Perfusion_study_radiomics/7971571/7971571_FLAIR.nii.gz
[[-4.42026973e-01 -7.97629431e-02  1.07396834e-01  1.32620529e+02]
 [ 7.90683702e-02 -4.40998703e-01 -5.08718789e-01  1.01953316e+02]
 [ 1.25626819e-02 -3.09108160e-02  6.98066425e+00 -4.28252144e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.42026975e-01  7.97629707e-02  1.0740

/media/sc-mlsg/DATA2/Perfusion_study_radiomics/8101370/8101370_FLAIR.nii.gz
[[-4.49019730e-01 -1.33191822e-02  1.81775745e-02  1.17876106e+02]
 [ 1.33701684e-02 -4.47307438e-01  6.10470176e-01  1.06135651e+02]
 [ 6.74102996e-11  3.91937457e-02  6.97330618e+00 -6.64891586e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.49019720e-01  1.33186337e-02  1.83730766e-02  1.11070000e+02]
 [ 1.33707167e-02  4.47307428e-01  6.10467271e-01 -1.22438454e+02]
 [ 1.25462390e-05 -3.91939346e-02  6.97330473e+00 -4.64611511e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
/media/sc-mlsg/DATA2/Perfusion_study_radiomics/8125034/8125034_FLAIR.nii.gz
[[-4.41332549e-01 -5.28442338e-02  1.01353419e+00  1.17374489e+02]
 [ 5.22795208e-02 -4.46099728e-01 -1.20061591e-01  1.07095528e+02]
 [ 6.54974133e-02 -3.00102859e-10  6.92519522e+00 -6.25574303e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.41332564e-01  5.28442358e-02  1.0135

/media/sc-mlsg/DATA2/Perfusion_study_radiomics/8494094/8494094_FLAIR.nii.gz
[[-4.47390497e-01 -4.01464067e-02  8.17113519e-02  1.25739227e+02]
 [ 3.92016359e-02 -4.44079906e-01 -8.61106277e-01  1.04698662e+02]
 [ 1.01223858e-02 -5.45782223e-02  6.94635296e+00 -2.85406170e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.47390532e-01  4.01462701e-02  8.16770321e-02  1.05224419e+02]
 [ 3.92017700e-02  4.44079913e-01 -8.61104944e-01 -1.22226166e+02]
 [ 1.01201816e-02  5.45783233e-02  6.94635447e+00 -5.64300880e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
/media/sc-mlsg/DATA2/Perfusion_study_radiomics/8513671/8513671_FLAIR.nii.gz
[[-4.48697597e-01  1.83948479e-03  3.35863411e-01  1.14037590e+02]
 [ 5.22070685e-11 -4.47591662e-01  5.95245123e-01  1.12998428e+02]
 [ 2.16320883e-02  3.81550044e-02  6.96655464e+00 -5.10884476e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.48697602e-01 -1.83948468e-03  3.3586

/media/sc-mlsg/DATA2/Perfusion_study_radiomics/8640861/8640861_FLAIR.nii.gz
[[-4.67683762e-01 -2.04634592e-02  3.33866179e-01  1.24263329e+02]
 [-2.79015880e-02  4.35085088e-01 -2.38768625e+00 -8.79674988e+01]
 [ 1.48307513e-02  1.73230410e-01  6.03634644e+00 -9.91091385e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.67683814e-01 -2.04636387e-02  3.33853220e-01  1.24263329e+02]
 [-2.79014104e-02  4.35085091e-01 -2.38768655e+00 -8.79674988e+01]
 [ 1.48298181e-02  1.73230384e-01  6.03634679e+00 -9.91091385e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
/media/sc-mlsg/DATA2/Perfusion_study_radiomics/8647046/8647046_FLAIR.nii.gz
[[-4.47387725e-01  3.69988009e-02  2.57372051e-01  1.01848312e+02]
 [-4.00431603e-02 -4.31694746e-01 -1.83277476e+00  1.29730240e+02]
 [ 6.18509855e-03 -1.18609563e-01  6.75090313e+00 -2.50597115e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.47387710e-01 -3.69987336e-02  2.5738

/media/sc-mlsg/DATA2/Perfusion_study_radiomics/9111662/9111662_FLAIR.nii.gz
[[-4.48836297e-01 -1.01610022e-02  2.41512448e-01  1.15696236e+02]
 [ 8.03940091e-03 -4.45243567e-01 -9.20695007e-01  1.15735840e+02]
 [ 1.66981500e-02 -5.87571003e-02  6.93498325e+00 -3.55550499e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.48836328e-01  1.01609521e-02  2.41500555e-01  1.10503960e+02]
 [ 8.03945152e-03  4.45243577e-01 -9.20694705e-01 -1.11783623e+02]
 [ 1.66973888e-02  5.87571079e-02  6.93498272e+00 -6.55799255e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
/media/sc-mlsg/DATA2/Perfusion_study_radiomics/6776630/6776630_FLAIR.nii.gz
[[-4.47956145e-01 -3.32395956e-02  8.22934508e-02  1.21170990e+02]
 [ 3.30103450e-02 -4.47659284e-01 -2.73898721e-01  1.21247696e+02]
 [ 6.56338735e-03 -1.71397254e-02  6.99415493e+00 -4.28711853e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-4.47956189e-01  3.32395647e-02  8.2262

In [9]:
for f, m in zip(resampled_flair, resampled_mask):
    img = nib.load(f)
    mask = nib.load(m)
    img_data = img.get_fdata()
    mask_data = mask.get_fdata()
    print(img_data.shape, mask_data.shape)

(250, 250, 180) (230, 230, 147)
(230, 230, 154) (230, 230, 154)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 154) (230, 230, 154)
(230, 230, 147) (230, 230, 150)
(230, 230, 140) (230, 230, 140)
(230, 230, 154) (230, 230, 154)
(230, 230, 140) (230, 230, 140)
(230, 230, 154) (230, 230, 154)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 154) (230, 230, 154)
(230, 230, 147) (230, 230, 147)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 154) (230, 230, 140)
(230, 230, 147) (230, 230, 147)
(230, 230, 147) (230, 230, 147)
(230, 230, 140) (230, 230, 140)
(230, 230, 147) (230, 230, 147)
(230, 230, 140) (230, 230, 140)
(230, 230, 147) (230, 230, 147)
(230, 230, 140) (230, 230, 140)
(230, 230, 150) (230, 230, 150)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 23

In [13]:
for f in registered:
    img = nib.load(f)
#        mask = nib.load(m)
    img_data = img.get_fdata()
#        mask_data = mask.get_fdata()
    print(img_data.shape)

(220, 220, 180)
(220, 220, 180)
(224, 224, 152)
(200, 200, 170)
(220, 220, 170)
(220, 220, 180)
(220, 220, 170)
(216, 216, 170)
(200, 200, 170)
(200, 200, 170)
(230, 230, 147)
(220, 220, 170)
(200, 200, 170)
(220, 220, 180)
(220, 220, 170)
(224, 224, 150)
(200, 200, 170)
(220, 220, 170)
(220, 220, 170)
(230, 230, 140)
(220, 220, 170)
(220, 220, 180)
(200, 200, 170)
(200, 200, 170)
(220, 220, 180)
(220, 220, 170)
(216, 216, 170)
(220, 220, 180)
(220, 220, 180)
(220, 220, 170)
(220, 220, 180)
(220, 220, 170)
(220, 220, 170)
(216, 216, 170)
(220, 220, 170)
(220, 220, 180)
(230, 230, 140)
(220, 220, 170)
(220, 220, 170)
(220, 220, 180)
(220, 220, 170)
(220, 220, 170)
(220, 220, 180)
(220, 220, 180)
(216, 216, 170)
(220, 220, 170)
(220, 220, 170)
(220, 220, 170)
(220, 220, 180)
(220, 220, 170)
(220, 220, 180)
(220, 220, 180)
(220, 220, 180)
(216, 216, 170)
(220, 220, 170)
(220, 220, 180)
(220, 220, 170)
(220, 220, 180)
(220, 220, 180)
(230, 230, 154)
(220, 220, 180)
(230, 230, 154)
(220, 22

In [7]:
for f, m in zip(registered_flair, resampled_mask):
    img = nib.load(f)
    mask = nib.load(m)
    img_data = img.get_fdata()
    mask_data = mask.get_fdata()
    print(img_data.shape, mask_data.shape)

(250, 250, 180) (230, 230, 147)
(230, 230, 154) (230, 230, 154)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 154) (230, 230, 154)
(230, 230, 147) (230, 230, 150)
(230, 230, 140) (230, 230, 140)
(230, 230, 154) (230, 230, 154)
(230, 230, 140) (230, 230, 140)
(230, 230, 154) (230, 230, 154)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 154) (230, 230, 154)
(230, 230, 147) (230, 230, 147)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 230, 154) (230, 230, 140)
(230, 230, 147) (230, 230, 147)
(230, 230, 147) (230, 230, 147)
(230, 230, 140) (230, 230, 140)
(230, 230, 147) (230, 230, 147)
(230, 230, 140) (230, 230, 140)
(230, 230, 147) (230, 230, 147)
(230, 230, 140) (230, 230, 140)
(230, 230, 150) (230, 230, 150)
(230, 230, 140) (230, 230, 140)
(230, 230, 140) (230, 230, 140)
(230, 23

ImageFileError: Empty file: '/media/sc-mlsg/DATA2/Perfusion_study_radiomics_preprocessed/03_Registered_corrected_F/7845251/7845251_FLAIR_registered.nii.gz'