In [2]:
import os
import shutil
import nibabel as nib
import numpy as np
from glob import glob
import SimpleITK as sitk

source = glob('/media/sc-mlsg/T7/Parkinson_data_copy/**/*.nii*')
print(len(source))

998


In [2]:
# check same patient has same img orientation
PATH = '/media/sc-mlsg/T7/Parkinson_data_copy/'
pt_lst = []
for (path, dirs, files) in os.walk(PATH):
    if files != []:
        pt = path.split(os.path.sep)[-1]
        for file in files:
            # load img
            img = nib.load(os.path.join(path, file))
           # print(file)
            if nib.aff2axcodes(img.affine) != ('L', 'P', 'S'):
                print(nib.aff2axcodes(img.affine))            
                print(file)
                pt_lst.append(pt)
    print()

print(set(pt_lst))








('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz



('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz






('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz





('P', 'I', 'L')
T2F.nii.gz



('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz


('L', 'I', 'P')
T1.nii.gz



('P', 'I', 'L')
T2F.nii.gz

('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz



('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz





('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz






('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz



('P', 'I', 'L')
T2F.nii.gz


('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz










('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz









('P', 'I', 'L')
T2F.nii.gz













('L', 'I', 'P')
T1.nii.gz


















('L', 'I', 'P')
T1.nii.gz







('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz


('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz







('P', 'I', 'L')
T1.nii.gz
('P', 'I', 'L')
T2F.nii.gz

('P', 'I',

In [16]:
pt_lst = list(set(pt_lst))
sourceDir = '/media/sc-mlsg/T7/Parkinson_data_preprocessed/BrainMask_corrected'

for filepath in os.listdir(sourceDir):
    pt = filepath.split('_')[0]
    if pt in pt_lst:
        print(pt)
        os.remove(os.path.join(sourceDir,filepath))

1531687
1831107
2223305
2450151
2594254
2638793
2816609
2974367
3071718
3157242
3375708
3563464
3963873
4365705
5067132
5294051
5328768
5354403
5585087
5767427
5798878
5881096
5906484
5922216
6779695
7242173
7759921
7803007
7821429
7918223
7941567
7943298
7958827
7960963
7979586
7988665
7990898
8054712
8064735
8082426
8119399
8122514
8186725
8225876
8226917
8293319


In [17]:
sorted(pt_lst)

['1531687',
 '1831107',
 '2223305',
 '2450151',
 '2594254',
 '2638793',
 '2816609',
 '2837756',
 '2870096',
 '2974367',
 '3071718',
 '3140501',
 '3157242',
 '3375708',
 '3563464',
 '3963873',
 '4365705',
 '5067132',
 '5120127',
 '5294051',
 '5328768',
 '5354403',
 '5434215',
 '5585087',
 '5767427',
 '5798878',
 '5881096',
 '5906484',
 '5922216',
 '6779695',
 '7242173',
 '7649292',
 '7759921',
 '7803007',
 '7821429',
 '7918223',
 '7941567',
 '7943298',
 '7958827',
 '7960963',
 '7977788',
 '7979586',
 '7988665',
 '7990898',
 '8054712',
 '8064735',
 '8082426',
 '8106080',
 '8119399',
 '8122514',
 '8186725',
 '8225876',
 '8226917',
 '8293319',
 '8403960']

1. header: PIL, img: LPI

2. header: LIP, img: LPS or LPI

In [9]:
import matplotlib.pyplot as plt
%matplotlib inline

source = glob('/media/sc-mlsg/T7/Parkinson_data_copy/**/*T2F_.*')
print(len(source))

# check whether img orientation is LPI or LPS
for filepath in source:
    # load img
    img = nib.load(filepath)    
    if nib.aff2axcodes(img.affine)[-1] == 'P':
        img_data = img.get_fdata()
        num_slices = img_data.shape[-1] 
        # set figure
        fig, axes = plt.subplots(ncols=3, nrows=1, figsize=(16, 12))
        fig.suptitle("Quality Check {}".format(filepath), fontsize=15)
        for i in range(3):
            axes[i].imshow(img_data[:,:,(num_slices*(i+1))//4].T, cmap="gray")


0


In [19]:
source = glob('/media/sc-mlsg/T7/Parkinson_data_copy/**/*T1_fl*')
print(len(source))

for filepath in source:
    # load img
    img = nib.load(filepath)    
    if nib.aff2axcodes(img.affine)[0] == 'A': # PIL -> LPS
        print(filepath.split(os.path.sep)[-2], filepath.split(os.path.sep)[-1])
        # print orientation of original img
        print(nib.aff2axcodes(img.affine))
        sitk_img = sitk.ReadImage(filepath)
        
        # reorient img(use np.flip or np.transpose)
        img_data = sitk.GetArrayFromImage(sitk_img)
        img_T = np.flip(img_data, axis=1)
        img_T = img_T.transpose(1, 2, 0)
        
        # reset image header info
        flipFilter = sitk.FlipImageFilter()
        
        flipAxes = (False, True, False) #(width, height, depth)
        flipFilter.SetFlipAxes(flipAxes)
        
        temp_img = flipFilter.Execute(sitk_img)
        
        new_img = sitk.PermuteAxes(temp_img, [2,0,1])
        
        # save new header info
        ni_img = sitk.GetImageFromArray(img_T)
        ni_img.SetOrigin(new_img.GetOrigin())
        ni_img.SetSpacing(new_img.GetSpacing())
        ni_img.SetDirection(new_img.GetDirection())
        
        # save file
        outpath = os.path.join(os.path.dirname(filepath), os.path.basename(filepath).split('.')[0]+'_flipped.nii.gz')
        
        sitk.WriteImage(ni_img, outpath)
        
        # check orientation of reoriented img
        img = nib.load(outpath)
        print(nib.aff2axcodes(img.affine))
        
        sitk_mask = sitk.ReadImage(outpath)
        print(np.array(sitk_mask.GetDirection()).reshape(3,3))

    if nib.aff2axcodes(img.affine)[-1] == 'P': # LIP -> LPS
        print(filepath.split(os.path.sep)[-2], filepath.split(os.path.sep)[-1])
        # print orientation of original img
        print(nib.aff2axcodes(img.affine))
        sitk_img = sitk.ReadImage(filepath)
        
        # reorient img(use np.flip or np.transpose)
        img_data = sitk.GetArrayFromImage(sitk_img)
        img_T = np.flip(img_data, axis=1)
        img_T = img_T.transpose(1, 0, 2)
        
        # reset image header info
        flipFilter = sitk.FlipImageFilter()
        
        flipAxes = (False, True, False) #(width, height, depth)
        flipFilter.SetFlipAxes(flipAxes)
        
        temp_img = flipFilter.Execute(sitk_img)
        
        new_img = sitk.PermuteAxes(temp_img, [0,2,1])
        
        # save new header info
        ni_img = sitk.GetImageFromArray(img_T)
        ni_img.SetOrigin(new_img.GetOrigin())
        ni_img.SetSpacing(new_img.GetSpacing())
        ni_img.SetDirection(new_img.GetDirection())
        
        # save file
        outpath = os.path.join(os.path.dirname(filepath), os.path.basename(filepath).split('.')[0]+'_flipped.nii.gz')
        
        sitk.WriteImage(ni_img, outpath)
        
        # check orientation of reoriented img
        img = nib.load(outpath)
        print(nib.aff2axcodes(img.affine))
        
        sitk_mask = sitk.ReadImage(outpath)
        print(np.array(sitk_mask.GetDirection()).reshape(3,3))


88
2638793 T1_flipped.nii.gz
('L', 'I', 'P')
('L', 'P', 'S')
[[ 0.9954788   0.03024794 -0.09003902]
 [-0.0289251   0.99945414  0.01596095]
 [ 0.09047265 -0.0132844   0.99581034]]
3963873 T1_flipped.nii.gz
('L', 'I', 'P')
('L', 'P', 'S')
[[ 0.99836557  0.05432789  0.01773903]
 [-0.05599606  0.99195737  0.11351215]
 [-0.01142949 -0.11431994  0.99337824]]
4365705 T1_flipped.nii.gz
('L', 'I', 'P')
('L', 'P', 'S')
[[ 0.99891657 -0.01705923 -0.04329742]
 [ 0.02475778  0.98260701  0.18403944]
 [ 0.03940478 -0.18491199  0.98196477]]
5434215 T1_flipped.nii.gz
('L', 'I', 'P')
('L', 'P', 'S')
[[ 0.99363172  0.11171244 -0.0147081 ]
 [-0.10772044  0.98008706  0.16681028]
 [ 0.03305    -0.16416362  0.9858793 ]]
7759921 T1_flipped.nii.gz
('L', 'I', 'P')
('L', 'P', 'S')
[[ 9.97633176e-01  1.51001888e-02 -6.70822670e-02]
 [ 4.60031407e-06  9.75574294e-01  2.19669745e-01]
 [ 6.87607946e-02 -2.19150132e-01  9.73265212e-01]]


In [12]:
source = glob('/media/sc-mlsg/T7/Parkinson_data_copy/**/*T1_fl*')
print(len(source))

88


In [10]:
# flip image only
for filepath in source[:20]:
    # load img
    img = nib.load(filepath)    
    if nib.aff2axcodes(img.affine)[0] == 'P': # LPI -> PIL 
        print(filepath.split(os.path.sep)[-2], filepath.split(os.path.sep)[-1])
        # print orientation of original img
        print(nib.aff2axcodes(img.affine))
        sitk_img = sitk.ReadImage(filepath)
        
        # reorient img(use np.flip or np.transpose)
        img_data = sitk.GetArrayFromImage(sitk_img)
        img_T = img_data.transpose(1, 0, 2)
#        img_T = np.flip(img_T, axis=2)
                
        # save file
        outpath = os.path.join(os.path.dirname(filepath), os.path.basename(filepath).split('.')[0]+'_flipped.nii.gz')

        ni_img = nib.Nifti1Image(img_T, img.affine, img.header)
        nib.save(ni_img, outpath)
                
        # check orientation of reoriented img
        img = nib.load(outpath)
        print(nib.aff2axcodes(img.affine))
        
        sitk_mask = sitk.ReadImage(outpath)
        print(np.array(sitk_mask.GetDirection()).reshape(3,3))
        
    if nib.aff2axcodes(img.affine)[-1] == 'A': # LPS -> LIP
        print(filepath.split(os.path.sep)[-2], filepath.split(os.path.sep)[-1])
        # print orientation of original img
        print(nib.aff2axcodes(img.affine))
        sitk_img = sitk.ReadImage(filepath)
        
        # reorient img(use np.flip or np.transpose)
        img_data = sitk.GetArrayFromImage(sitk_img)
        img_T = img_data.transpose(2, 0, 1)
        img_T = np.flip(img_T, axis=1)
                
        # save file
        outpath = os.path.join(os.path.dirname(filepath), os.path.basename(filepath).split('.')[0]+'_flipped_2.nii.gz')
        
        ni_img = nib.Nifti1Image(img_T, img.affine, img.header)
        nib.save(ni_img, outpath)
                
        # check orientation of reoriented img
        img = nib.load(outpath)
        print(nib.aff2axcodes(img.affine))
        
        sitk_mask = sitk.ReadImage(outpath)
        print(np.array(sitk_mask.GetDirection()).reshape(3,3))


1531687 T1.nii.gz
('P', 'I', 'L')
('P', 'I', 'L')
[[-0.05390628  0.00515339  0.9985327 ]
 [ 0.98995183  0.13119115  0.05276596]
 [ 0.13072673 -0.9913437   0.01217363]]
1831107 T1.nii.gz
('P', 'I', 'L')
('P', 'I', 'L')
[[-0.00612172  0.01813791  0.99981675]
 [ 0.99575412 -0.09172514  0.00776085]
 [-0.0918491  -0.99561916  0.01749938]]
2223305 T1.nii.gz
('P', 'I', 'L')
('P', 'I', 'L')
[[-1.03991757e-02  3.28436670e-02  9.99406399e-01]
 [ 9.99945927e-01  3.41582917e-04  1.03935637e-02]
 [ 1.74058429e-08 -9.99460443e-01  3.28454413e-02]]
